x-rust-image: &rust-image cdcgov/mira-oxide:latest
x-data-volume: &data-volume
  type: bind
  source: /home/xpa3/mira-oxide/test
  target: /data

services:
  mira-oxide:
    container_name: mira-oxide
    image: cdcgov/mira-oxide:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - *data-volume
    command: tail -f /dev/null
