[package]
name = "plots"
version = "0.1.0"
authors = ["Ben Rambo-Martin <brambomartin@cdc.gov>"]
edition = "2024"

[dependencies]
csv.workspace = true
glob = "0.3.2"
ordered-float = "5.0.0"
#plotly = "0.12.1"
plotly = { git = "https://github.com/plotly/plotly.rs.git", branch = "main" }