[package]
name = "plots"
version = "0.1.0"
authors = ["Ben Rambo-Martin <brambomartin@cdc.gov>"]
edition = "2024"

[dependencies]
csv.workspace = true
clap.workspace = true
glob.workspace = true
ordered-float.workspace = true
plotly.workspace = true