[package]
name = "di_stats"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
glob = "0.3"
regex = "1"
clap = { version = "4.5", features = ["derive"] }
