[package]
name = "flu_prepare_irma_json"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
csv = "1.3.1"
either = "1"
serde = {version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9"