[package]
name = "variants_of_interest_table"
version = "0.2.1"
edition = "2024"

[dependencies]
clap.workspace = true
csv.workspace = true
either.workspace = true
serde = {version = "1.0.219", features = ["derive"] }

zoe.workspace = true